import './SampleWebApp.css';

const SampleWebApp = () => {
    return (
        <div className = "WebAppWrapper">
        <p><b>This is where you can put the main UI elements of your web app.</b></p>
        <p><b>For now, have some dummy text.</b></p>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Purus gravida quis blandit turpis cursus in hac habitasse platea. In est ante in nibh mauris cursus mattis molestie a. Etiam sit amet nisl purus in mollis nunc sed id. Ultrices gravida dictum fusce ut placerat orci nulla. Non diam phasellus vestibulum lorem sed risus ultricies. At consectetur lorem donec massa sapien faucibus et. Sit amet cursus sit amet. Non quam lacus suspendisse faucibus interdum. Enim ut tellus elementum sagittis vitae et leo duis. Velit sed ullamcorper morbi tincidunt ornare massa eget egestas. Risus nec feugiat in fermentum posuere urna nec tincidunt praesent. Enim nulla aliquet porttitor lacus luctus accumsan. Mattis vulputate enim nulla aliquet porttitor lacus. Pharetra massa massa ultricies mi. Orci phasellus egestas tellus rutrum. Lectus vestibulum mattis ullamcorper velit sed ullamcorper morbi.</p>
        <p>Augue ut lectus arcu bibendum at. Et ultrices neque ornare aenean euismod elementum nisi. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Consequat nisl vel pretium lectus quam id. Orci phasellus egestas tellus rutrum tellus pellentesque eu. Erat imperdiet sed euismod nisi porta. Tellus mauris a diam maecenas sed enim ut sem. Quam nulla porttitor massa id. Tortor condimentum lacinia quis vel eros donec ac odio tempor. Vulputate dignissim suspendisse in est. Sit amet consectetur adipiscing elit. Donec et odio pellentesque diam volutpat commodo sed egestas. At urna condimentum mattis pellentesque id nibh tortor. Quam vulputate dignissim suspendisse in est ante in. Sagittis vitae et leo duis ut diam quam nulla. In cursus turpis massa tincidunt dui. Quam quisque id diam vel quam. Feugiat sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Sit amet est placerat in egestas erat imperdiet sed euismod.</p>
        <p>Eu non diam phasellus vestibulum lorem sed. Et malesuada fames ac turpis egestas integer eget. Faucibus scelerisque eleifend donec pretium vulputate sapien nec. Donec massa sapien faucibus et. Turpis egestas maecenas pharetra convallis. Amet justo donec enim diam vulputate. Cras ornare arcu dui vivamus arcu felis bibendum. Pellentesque massa placerat duis ultricies. Sagittis id consectetur purus ut faucibus. A diam maecenas sed enim ut sem viverra. Habitant morbi tristique senectus et netus. Interdum posuere lorem ipsum dolor sit amet consectetur adipiscing elit.</p>
        <p>Augue neque gravida in fermentum et sollicitudin ac orci phasellus. Venenatis lectus magna fringilla urna porttitor rhoncus. Vulputate enim nulla aliquet porttitor lacus luctus accumsan. Eu ultrices vitae auctor eu augue ut lectus. Hac habitasse platea dictumst vestibulum. Nulla facilisi cras fermentum odio eu feugiat pretium nibh. Arcu bibendum at varius vel pharetra vel turpis nunc. Sit amet tellus cras adipiscing. Dictumst quisque sagittis purus sit amet volutpat. Fermentum odio eu feugiat pretium nibh. Egestas diam in arcu cursus. Mauris commodo quis imperdiet massa tincidunt nunc pulvinar sapien. Enim facilisis gravida neque convallis a cras semper auctor neque. Libero justo laoreet sit amet cursus sit. Arcu risus quis varius quam quisque id. Sagittis vitae et leo duis ut. Fringilla urna porttitor rhoncus dolor purus non enim praesent. Blandit volutpat maecenas volutpat blandit aliquam. Non diam phasellus vestibulum lorem sed risus ultricies.</p>
        <p>Mi proin sed libero enim sed faucibus turpis in. Risus feugiat in ante metus dictum at tempor commodo ullamcorper. Tellus integer feugiat scelerisque varius. Amet tellus cras adipiscing enim eu turpis egestas pretium. Pellentesque eu tincidunt tortor aliquam nulla facilisi cras fermentum. Dictum varius duis at consectetur lorem donec massa sapien. Magna eget est lorem ipsum. Erat imperdiet sed euismod nisi porta lorem mollis aliquam. Ipsum dolor sit amet consectetur adipiscing elit. Nisi lacus sed viverra tellus in hac habitasse platea. Est pellentesque elit ullamcorper dignissim cras. Quam lacus suspendisse faucibus interdum posuere lorem ipsum. Sit amet consectetur adipiscing elit ut aliquam purus sit amet. Diam vulputate ut pharetra sit amet aliquam id. Lorem ipsum dolor sit amet consectetur adipiscing elit.</p>
        </div>
    );
}

export default SampleWebApp;